package org.osgi.test.assertj.dto.resource.dto;

import org.assertj.core.api.AbstractObjectAssert;
import org.osgi.resource.dto.CapabilityRefDTO;

/**
 * Abstract base class for {@link CapabilityRefDTO} specific assertions - Generated by CustomAssertionGenerator.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public abstract class AbstractCapabilityRefDTOAssert<S extends AbstractCapabilityRefDTOAssert<S, A>, A extends CapabilityRefDTO> extends AbstractObjectAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractCapabilityRefDTOAssert}</code> to make assertions on actual CapabilityRefDTO.
   * @param actual the CapabilityRefDTO we want to make assertions on.
   */
  protected AbstractCapabilityRefDTOAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

  /**
   * Verifies that the actual CapabilityRefDTO's capability is equal to the given one.
   * @param capability the given capability to compare the actual CapabilityRefDTO's capability to.
   * @return this assertion object.
   * @throws AssertionError - if the actual CapabilityRefDTO's capability is not equal to the given one.
   */
  public S hasCapability(int capability) {
    // check that actual CapabilityRefDTO we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting capability of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // check
    int actualCapability = actual.capability;
    if (actualCapability != capability) {
      failWithMessage(assertjErrorMessage, actual, capability, actualCapability);
    }

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual CapabilityRefDTO's resource is equal to the given one.
   * @param resource the given resource to compare the actual CapabilityRefDTO's resource to.
   * @return this assertion object.
   * @throws AssertionError - if the actual CapabilityRefDTO's resource is not equal to the given one.
   */
  public S hasResource(int resource) {
    // check that actual CapabilityRefDTO we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting resource of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // check
    int actualResource = actual.resource;
    if (actualResource != resource) {
      failWithMessage(assertjErrorMessage, actual, resource, actualResource);
    }

    // return the current assertion for method chaining
    return myself;
  }

}
