package org.osgi.test.assertj.dto.resource.dto;

import org.osgi.resource.dto.CapabilityRefDTO;

/**
 * {@link CapabilityRefDTO} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractCapabilityRefDTOAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class CapabilityRefDTOAssert extends AbstractCapabilityRefDTOAssert<CapabilityRefDTOAssert, CapabilityRefDTO> {

  /**
   * Creates a new <code>{@link CapabilityRefDTOAssert}</code> to make assertions on actual CapabilityRefDTO.
   * @param actual the CapabilityRefDTO we want to make assertions on.
   */
  public CapabilityRefDTOAssert(CapabilityRefDTO actual) {
    super(actual, CapabilityRefDTOAssert.class);
  }

  /**
   * An entry point for CapabilityRefDTOAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myCapabilityRefDTO)</code> and get specific assertion with code completion.
   * @param actual the CapabilityRefDTO we want to make assertions on.
   * @return a new <code>{@link CapabilityRefDTOAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static CapabilityRefDTOAssert assertThat(CapabilityRefDTO actual) {
    return new CapabilityRefDTOAssert(actual);
  }
}
