package org.osgi.test.assertj.dto.resource.dto;

import org.osgi.resource.dto.WireDTO;

/**
 * {@link WireDTO} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractWireDTOAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class WireDTOAssert extends AbstractWireDTOAssert<WireDTOAssert, WireDTO> {

  /**
   * Creates a new <code>{@link WireDTOAssert}</code> to make assertions on actual WireDTO.
   * @param actual the WireDTO we want to make assertions on.
   */
  public WireDTOAssert(WireDTO actual) {
    super(actual, WireDTOAssert.class);
  }

  /**
   * An entry point for WireDTOAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myWireDTO)</code> and get specific assertion with code completion.
   * @param actual the WireDTO we want to make assertions on.
   * @return a new <code>{@link WireDTOAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static WireDTOAssert assertThat(WireDTO actual) {
    return new WireDTOAssert(actual);
  }
}
