package org.osgi.test.assertj.dto.framework.startlevel.dto;

import org.osgi.framework.startlevel.dto.FrameworkStartLevelDTO;

/**
 * {@link FrameworkStartLevelDTO} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractFrameworkStartLevelDTOAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class FrameworkStartLevelDTOAssert extends AbstractFrameworkStartLevelDTOAssert<FrameworkStartLevelDTOAssert, FrameworkStartLevelDTO> {

  /**
   * Creates a new <code>{@link FrameworkStartLevelDTOAssert}</code> to make assertions on actual FrameworkStartLevelDTO.
   * @param actual the FrameworkStartLevelDTO we want to make assertions on.
   */
  public FrameworkStartLevelDTOAssert(FrameworkStartLevelDTO actual) {
    super(actual, FrameworkStartLevelDTOAssert.class);
  }

  /**
   * An entry point for FrameworkStartLevelDTOAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myFrameworkStartLevelDTO)</code> and get specific assertion with code completion.
   * @param actual the FrameworkStartLevelDTO we want to make assertions on.
   * @return a new <code>{@link FrameworkStartLevelDTOAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static FrameworkStartLevelDTOAssert assertThat(FrameworkStartLevelDTO actual) {
    return new FrameworkStartLevelDTOAssert(actual);
  }
}
