package org.osgi.test.assertj.dto.service.http.runtime.dto;

import org.osgi.service.http.runtime.dto.FailedFilterDTO;

/**
 * Abstract base class for {@link FailedFilterDTO} specific assertions - Generated by CustomAssertionGenerator.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public abstract class AbstractFailedFilterDTOAssert<S extends AbstractFailedFilterDTOAssert<S, A>, A extends FailedFilterDTO> extends AbstractFilterDTOAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractFailedFilterDTOAssert}</code> to make assertions on actual FailedFilterDTO.
   * @param actual the FailedFilterDTO we want to make assertions on.
   */
  protected AbstractFailedFilterDTOAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

  /**
   * Verifies that the actual FailedFilterDTO's failureReason is equal to the given one.
   * @param failureReason the given failureReason to compare the actual FailedFilterDTO's failureReason to.
   * @return this assertion object.
   * @throws AssertionError - if the actual FailedFilterDTO's failureReason is not equal to the given one.
   */
  public S hasFailureReason(int failureReason) {
    // check that actual FailedFilterDTO we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting failureReason of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // check
    int actualFailureReason = actual.failureReason;
    if (actualFailureReason != failureReason) {
      failWithMessage(assertjErrorMessage, actual, failureReason, actualFailureReason);
    }

    // return the current assertion for method chaining
    return myself;
  }

}
