package org.osgi.test.assertj.dto.service.http.runtime.dto;

import org.assertj.core.api.AbstractObjectAssert;
import org.assertj.core.api.Assertions;
import org.osgi.service.http.runtime.dto.ListenerDTO;

/**
 * Abstract base class for {@link ListenerDTO} specific assertions - Generated by CustomAssertionGenerator.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public abstract class AbstractListenerDTOAssert<S extends AbstractListenerDTOAssert<S, A>, A extends ListenerDTO> extends AbstractObjectAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractListenerDTOAssert}</code> to make assertions on actual ListenerDTO.
   * @param actual the ListenerDTO we want to make assertions on.
   */
  protected AbstractListenerDTOAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

  /**
   * Verifies that the actual ListenerDTO's serviceId is equal to the given one.
   * @param serviceId the given serviceId to compare the actual ListenerDTO's serviceId to.
   * @return this assertion object.
   * @throws AssertionError - if the actual ListenerDTO's serviceId is not equal to the given one.
   */
  public S hasServiceId(long serviceId) {
    // check that actual ListenerDTO we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting serviceId of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // check
    long actualServiceId = actual.serviceId;
    if (actualServiceId != serviceId) {
      failWithMessage(assertjErrorMessage, actual, serviceId, actualServiceId);
    }

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual ListenerDTO's servletContextId is equal to the given one.
   * @param servletContextId the given servletContextId to compare the actual ListenerDTO's servletContextId to.
   * @return this assertion object.
   * @throws AssertionError - if the actual ListenerDTO's servletContextId is not equal to the given one.
   */
  public S hasServletContextId(long servletContextId) {
    // check that actual ListenerDTO we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting servletContextId of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // check
    long actualServletContextId = actual.servletContextId;
    if (actualServletContextId != servletContextId) {
      failWithMessage(assertjErrorMessage, actual, servletContextId, actualServletContextId);
    }

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual ListenerDTO's types contains the given String elements.
   * @param types the given elements that should be contained in actual ListenerDTO's types.
   * @return this assertion object.
   * @throws AssertionError if the actual ListenerDTO's types does not contain all given String elements.
   */
  public S hasTypes(String... types) {
    // check that actual ListenerDTO we want to make assertions on is not null.
    isNotNull();

    // check that given String varargs is not null.
    if (types == null) failWithMessage("Expecting types parameter not to be null.");

    // check with standard error message (use overridingErrorMessage before contains to set your own message).
    Assertions.assertThat(actual.types).contains(types);

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual ListenerDTO's types contains <b>only</b> the given String elements and nothing else in whatever order.
   *
   * @param types the given elements that should be contained in actual ListenerDTO's types.
   * @return this assertion object.
   * @throws AssertionError if the actual ListenerDTO's types does not contain all given String elements and nothing else.
   */
  public S hasOnlyTypes(String... types) {
    // check that actual ListenerDTO we want to make assertions on is not null.
    isNotNull();

    // check that given String varargs is not null.
    if (types == null) failWithMessage("Expecting types parameter not to be null.");

    // check with standard error message (use overridingErrorMessage before contains to set your own message).
    Assertions.assertThat(actual.types).containsOnly(types);

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual ListenerDTO's types does not contain the given String elements.
   *
   * @param types the given elements that should not be in actual ListenerDTO's types.
   * @return this assertion object.
   * @throws AssertionError if the actual ListenerDTO's types contains any given String elements.
   */
  public S doesNotHaveTypes(String... types) {
    // check that actual ListenerDTO we want to make assertions on is not null.
    isNotNull();

    // check that given String varargs is not null.
    if (types == null) failWithMessage("Expecting types parameter not to be null.");

    // check with standard error message (use overridingErrorMessage before contains to set your own message).
    Assertions.assertThat(actual.types).doesNotContain(types);

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual ListenerDTO has no types.
   * @return this assertion object.
   * @throws AssertionError if the actual ListenerDTO's types is not empty.
   */
  public S hasNoTypes() {
    // check that actual ListenerDTO we want to make assertions on is not null.
    isNotNull();

    // we override the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting :\n  <%s>\nnot to have types but had :\n  <%s>";

    // check that it is not empty
    if (actual.types.length > 0)  {
      failWithMessage(assertjErrorMessage, actual, java.util.Arrays.toString(actual.types));
    }

    // return the current assertion for method chaining
    return myself;
  }


}
