package org.osgi.test.assertj.dto.service.http.runtime.dto;

import org.osgi.service.http.runtime.dto.BaseServletDTO;

/**
 * {@link BaseServletDTO} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractBaseServletDTOAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class BaseServletDTOAssert extends AbstractBaseServletDTOAssert<BaseServletDTOAssert, BaseServletDTO> {

  /**
   * Creates a new <code>{@link BaseServletDTOAssert}</code> to make assertions on actual BaseServletDTO.
   * @param actual the BaseServletDTO we want to make assertions on.
   */
  public BaseServletDTOAssert(BaseServletDTO actual) {
    super(actual, BaseServletDTOAssert.class);
  }

  /**
   * An entry point for BaseServletDTOAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myBaseServletDTO)</code> and get specific assertion with code completion.
   * @param actual the BaseServletDTO we want to make assertions on.
   * @return a new <code>{@link BaseServletDTOAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static BaseServletDTOAssert assertThat(BaseServletDTO actual) {
    return new BaseServletDTOAssert(actual);
  }
}
