package org.osgi.test.assertj.dto.service.http.runtime.dto;

import org.osgi.service.http.runtime.dto.ErrorPageDTO;

/**
 * {@link ErrorPageDTO} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractErrorPageDTOAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class ErrorPageDTOAssert extends AbstractErrorPageDTOAssert<ErrorPageDTOAssert, ErrorPageDTO> {

  /**
   * Creates a new <code>{@link ErrorPageDTOAssert}</code> to make assertions on actual ErrorPageDTO.
   * @param actual the ErrorPageDTO we want to make assertions on.
   */
  public ErrorPageDTOAssert(ErrorPageDTO actual) {
    super(actual, ErrorPageDTOAssert.class);
  }

  /**
   * An entry point for ErrorPageDTOAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myErrorPageDTO)</code> and get specific assertion with code completion.
   * @param actual the ErrorPageDTO we want to make assertions on.
   * @return a new <code>{@link ErrorPageDTOAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static ErrorPageDTOAssert assertThat(ErrorPageDTO actual) {
    return new ErrorPageDTOAssert(actual);
  }
}
