package org.osgi.test.assertj.dto.service.http.runtime.dto;

import org.osgi.service.http.runtime.dto.FailedServletContextDTO;

/**
 * {@link FailedServletContextDTO} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractFailedServletContextDTOAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class FailedServletContextDTOAssert extends AbstractFailedServletContextDTOAssert<FailedServletContextDTOAssert, FailedServletContextDTO> {

  /**
   * Creates a new <code>{@link FailedServletContextDTOAssert}</code> to make assertions on actual FailedServletContextDTO.
   * @param actual the FailedServletContextDTO we want to make assertions on.
   */
  public FailedServletContextDTOAssert(FailedServletContextDTO actual) {
    super(actual, FailedServletContextDTOAssert.class);
  }

  /**
   * An entry point for FailedServletContextDTOAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myFailedServletContextDTO)</code> and get specific assertion with code completion.
   * @param actual the FailedServletContextDTO we want to make assertions on.
   * @return a new <code>{@link FailedServletContextDTOAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static FailedServletContextDTOAssert assertThat(FailedServletContextDTO actual) {
    return new FailedServletContextDTOAssert(actual);
  }
}
