package org.osgi.test.assertj.dto.service.http.runtime.dto;

import org.osgi.service.http.runtime.dto.FailedServletDTO;

/**
 * {@link FailedServletDTO} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractFailedServletDTOAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class FailedServletDTOAssert extends AbstractFailedServletDTOAssert<FailedServletDTOAssert, FailedServletDTO> {

  /**
   * Creates a new <code>{@link FailedServletDTOAssert}</code> to make assertions on actual FailedServletDTO.
   * @param actual the FailedServletDTO we want to make assertions on.
   */
  public FailedServletDTOAssert(FailedServletDTO actual) {
    super(actual, FailedServletDTOAssert.class);
  }

  /**
   * An entry point for FailedServletDTOAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myFailedServletDTO)</code> and get specific assertion with code completion.
   * @param actual the FailedServletDTO we want to make assertions on.
   * @return a new <code>{@link FailedServletDTOAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static FailedServletDTOAssert assertThat(FailedServletDTO actual) {
    return new FailedServletDTOAssert(actual);
  }
}
