package org.osgi.test.assertj.dto.service.http.runtime.dto;

import org.osgi.service.http.runtime.dto.FailedFilterDTO;

/**
 * {@link FailedFilterDTO} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractFailedFilterDTOAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class FailedFilterDTOAssert extends AbstractFailedFilterDTOAssert<FailedFilterDTOAssert, FailedFilterDTO> {

  /**
   * Creates a new <code>{@link FailedFilterDTOAssert}</code> to make assertions on actual FailedFilterDTO.
   * @param actual the FailedFilterDTO we want to make assertions on.
   */
  public FailedFilterDTOAssert(FailedFilterDTO actual) {
    super(actual, FailedFilterDTOAssert.class);
  }

  /**
   * An entry point for FailedFilterDTOAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myFailedFilterDTO)</code> and get specific assertion with code completion.
   * @param actual the FailedFilterDTO we want to make assertions on.
   * @return a new <code>{@link FailedFilterDTOAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static FailedFilterDTOAssert assertThat(FailedFilterDTO actual) {
    return new FailedFilterDTOAssert(actual);
  }
}
