package org.osgi.test.assertj.dto.service.http.runtime.dto;

import org.osgi.service.http.runtime.dto.FilterDTO;

/**
 * {@link FilterDTO} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractFilterDTOAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class FilterDTOAssert extends AbstractFilterDTOAssert<FilterDTOAssert, FilterDTO> {

  /**
   * Creates a new <code>{@link FilterDTOAssert}</code> to make assertions on actual FilterDTO.
   * @param actual the FilterDTO we want to make assertions on.
   */
  public FilterDTOAssert(FilterDTO actual) {
    super(actual, FilterDTOAssert.class);
  }

  /**
   * An entry point for FilterDTOAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myFilterDTO)</code> and get specific assertion with code completion.
   * @param actual the FilterDTO we want to make assertions on.
   * @return a new <code>{@link FilterDTOAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static FilterDTOAssert assertThat(FilterDTO actual) {
    return new FilterDTOAssert(actual);
  }
}
