package org.osgi.test.assertj.dto.service.http.runtime.dto;

import org.osgi.service.http.runtime.dto.ResourceDTO;

/**
 * {@link ResourceDTO} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractResourceDTOAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class ResourceDTOAssert extends AbstractResourceDTOAssert<ResourceDTOAssert, ResourceDTO> {

  /**
   * Creates a new <code>{@link ResourceDTOAssert}</code> to make assertions on actual ResourceDTO.
   * @param actual the ResourceDTO we want to make assertions on.
   */
  public ResourceDTOAssert(ResourceDTO actual) {
    super(actual, ResourceDTOAssert.class);
  }

  /**
   * An entry point for ResourceDTOAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myResourceDTO)</code> and get specific assertion with code completion.
   * @param actual the ResourceDTO we want to make assertions on.
   * @return a new <code>{@link ResourceDTOAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static ResourceDTOAssert assertThat(ResourceDTO actual) {
    return new ResourceDTOAssert(actual);
  }
}
