package org.osgi.test.assertj.dto.service.http.runtime.dto;

import org.osgi.service.http.runtime.dto.RuntimeDTO;

/**
 * {@link RuntimeDTO} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractRuntimeDTOAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class RuntimeDTOAssert extends AbstractRuntimeDTOAssert<RuntimeDTOAssert, RuntimeDTO> {

  /**
   * Creates a new <code>{@link RuntimeDTOAssert}</code> to make assertions on actual RuntimeDTO.
   * @param actual the RuntimeDTO we want to make assertions on.
   */
  public RuntimeDTOAssert(RuntimeDTO actual) {
    super(actual, RuntimeDTOAssert.class);
  }

  /**
   * An entry point for RuntimeDTOAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myRuntimeDTO)</code> and get specific assertion with code completion.
   * @param actual the RuntimeDTO we want to make assertions on.
   * @return a new <code>{@link RuntimeDTOAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static RuntimeDTOAssert assertThat(RuntimeDTO actual) {
    return new RuntimeDTOAssert(actual);
  }
}
