package org.osgi.test.assertj.dto.service.http.runtime.dto;

import org.osgi.service.http.runtime.dto.ServletDTO;

/**
 * {@link ServletDTO} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractServletDTOAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class ServletDTOAssert extends AbstractServletDTOAssert<ServletDTOAssert, ServletDTO> {

  /**
   * Creates a new <code>{@link ServletDTOAssert}</code> to make assertions on actual ServletDTO.
   * @param actual the ServletDTO we want to make assertions on.
   */
  public ServletDTOAssert(ServletDTO actual) {
    super(actual, ServletDTOAssert.class);
  }

  /**
   * An entry point for ServletDTOAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myServletDTO)</code> and get specific assertion with code completion.
   * @param actual the ServletDTO we want to make assertions on.
   * @return a new <code>{@link ServletDTOAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static ServletDTOAssert assertThat(ServletDTO actual) {
    return new ServletDTOAssert(actual);
  }
}
