package org.osgi.test.assertj.dto.service.component.runtime.dto;

import org.osgi.service.component.runtime.dto.ReferenceDTO;

/**
 * {@link ReferenceDTO} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractReferenceDTOAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class ReferenceDTOAssert extends AbstractReferenceDTOAssert<ReferenceDTOAssert, ReferenceDTO> {

  /**
   * Creates a new <code>{@link ReferenceDTOAssert}</code> to make assertions on actual ReferenceDTO.
   * @param actual the ReferenceDTO we want to make assertions on.
   */
  public ReferenceDTOAssert(ReferenceDTO actual) {
    super(actual, ReferenceDTOAssert.class);
  }

  /**
   * An entry point for ReferenceDTOAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myReferenceDTO)</code> and get specific assertion with code completion.
   * @param actual the ReferenceDTO we want to make assertions on.
   * @return a new <code>{@link ReferenceDTOAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static ReferenceDTOAssert assertThat(ReferenceDTO actual) {
    return new ReferenceDTOAssert(actual);
  }
}
