package org.osgi.test.assertj.dto.service.component.runtime.dto;

import org.osgi.service.component.runtime.dto.SatisfiedReferenceDTO;

/**
 * {@link SatisfiedReferenceDTO} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractSatisfiedReferenceDTOAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class SatisfiedReferenceDTOAssert extends AbstractSatisfiedReferenceDTOAssert<SatisfiedReferenceDTOAssert, SatisfiedReferenceDTO> {

  /**
   * Creates a new <code>{@link SatisfiedReferenceDTOAssert}</code> to make assertions on actual SatisfiedReferenceDTO.
   * @param actual the SatisfiedReferenceDTO we want to make assertions on.
   */
  public SatisfiedReferenceDTOAssert(SatisfiedReferenceDTO actual) {
    super(actual, SatisfiedReferenceDTOAssert.class);
  }

  /**
   * An entry point for SatisfiedReferenceDTOAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(mySatisfiedReferenceDTO)</code> and get specific assertion with code completion.
   * @param actual the SatisfiedReferenceDTO we want to make assertions on.
   * @return a new <code>{@link SatisfiedReferenceDTOAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static SatisfiedReferenceDTOAssert assertThat(SatisfiedReferenceDTO actual) {
    return new SatisfiedReferenceDTOAssert(actual);
  }
}
