package org.osgi.test.assertj.dto.framework.wiring.dto;

import org.osgi.framework.wiring.dto.BundleWireDTO;

/**
 * {@link BundleWireDTO} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractBundleWireDTOAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class BundleWireDTOAssert extends AbstractBundleWireDTOAssert<BundleWireDTOAssert, BundleWireDTO> {

  /**
   * Creates a new <code>{@link BundleWireDTOAssert}</code> to make assertions on actual BundleWireDTO.
   * @param actual the BundleWireDTO we want to make assertions on.
   */
  public BundleWireDTOAssert(BundleWireDTO actual) {
    super(actual, BundleWireDTOAssert.class);
  }

  /**
   * An entry point for BundleWireDTOAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myBundleWireDTO)</code> and get specific assertion with code completion.
   * @param actual the BundleWireDTO we want to make assertions on.
   * @return a new <code>{@link BundleWireDTOAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static BundleWireDTOAssert assertThat(BundleWireDTO actual) {
    return new BundleWireDTOAssert(actual);
  }
}
