package org.osgi.test.assertj.dto.framework.wiring.dto;

import org.osgi.framework.wiring.dto.BundleRevisionDTO;

/**
 * {@link BundleRevisionDTO} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractBundleRevisionDTOAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class BundleRevisionDTOAssert extends AbstractBundleRevisionDTOAssert<BundleRevisionDTOAssert, BundleRevisionDTO> {

  /**
   * Creates a new <code>{@link BundleRevisionDTOAssert}</code> to make assertions on actual BundleRevisionDTO.
   * @param actual the BundleRevisionDTO we want to make assertions on.
   */
  public BundleRevisionDTOAssert(BundleRevisionDTO actual) {
    super(actual, BundleRevisionDTOAssert.class);
  }

  /**
   * An entry point for BundleRevisionDTOAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myBundleRevisionDTO)</code> and get specific assertion with code completion.
   * @param actual the BundleRevisionDTO we want to make assertions on.
   * @return a new <code>{@link BundleRevisionDTOAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static BundleRevisionDTOAssert assertThat(BundleRevisionDTO actual) {
    return new BundleRevisionDTOAssert(actual);
  }
}
