/*******************************************************************************
 * Copyright (c) Contributors to the Eclipse Foundation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 *******************************************************************************/

package org.osgi.test.assertj.feature;

import java.util.List;
import java.util.Map;
import java.util.Objects;

import org.assertj.core.api.AbstractObjectAssert;
import org.assertj.core.api.InstanceOfAssertFactories;
import org.assertj.core.api.InstanceOfAssertFactory;
import org.assertj.core.api.ListAssert;
import org.assertj.core.api.MapAssert;
import org.osgi.service.feature.Feature;
import org.osgi.service.feature.FeatureBundle;
import org.osgi.service.feature.FeatureConfiguration;
import org.osgi.service.feature.FeatureExtension;

/**
 * Abstract base class for {@link Feature} specific assertions - Generated by
 * CustomAssertionGenerator.
 */
public abstract class AbstractFeatureAssert<S extends AbstractFeatureAssert<S, A>, A extends Feature>
	extends AbstractObjectAssert<S, A> {

	/**
	 * Creates a new <code>{@link AbstractFeatureAssert}</code> to make
	 * assertions on actual Feature.
	 *
	 * @param actual the Feature we want to make assertions on.
	 */
	protected AbstractFeatureAssert(A actual, Class<S> selfType) {
		super(actual, selfType);
	}

	public IDAssert hasIDThat() {
		isNotNull();
		return IDAssert.assertThat(actual.getID())
			.as(actual + ".id");
	}

	@SuppressWarnings("rawtypes")
	static InstanceOfAssertFactory<List, ListAssert<FeatureBundle>>					BUNDLE_LIST		= InstanceOfAssertFactories
		.list(FeatureBundle.class);

	@SuppressWarnings("rawtypes")
	static InstanceOfAssertFactory<Map, MapAssert<String, FeatureConfiguration>>	CONFIG_MAP		= InstanceOfAssertFactories
		.map(String.class, FeatureConfiguration.class);

	@SuppressWarnings("rawtypes")
	static InstanceOfAssertFactory<Map, MapAssert<String, FeatureExtension>>		EXTENSION_MAP	= InstanceOfAssertFactories
		.map(String.class, FeatureExtension.class);

	@SuppressWarnings("rawtypes")
	static InstanceOfAssertFactory<Map, MapAssert<String, String>>					VARIABLE_MAP	= InstanceOfAssertFactories
		.map(String.class, String.class);

	public ListAssert<FeatureBundle> hasBundlesThat() {
		return isNotNull().extracting(f -> f.getBundles(), BUNDLE_LIST)
			.as(actual + ".bundles");
	}

	public MapAssert<String, FeatureConfiguration> hasConfigurationsThat() {
		return isNotNull().extracting(f -> f.getConfigurations(), CONFIG_MAP)
			.as(actual + ".configurations");
	}

	public MapAssert<String, FeatureExtension> hasExtensionsThat() {
		return isNotNull().extracting(f -> f.getExtensions(), EXTENSION_MAP)
			.as(actual + ".extensions");
	}

	public MapAssert<String, String> hasVariablesThat() {
		return isNotNull().extracting(f -> f.getVariables(), VARIABLE_MAP)
			.as(actual + ".variables");
	}

	/**
	 * Verifies that the actual Feature is complete.
	 *
	 * @return this assertion object.
	 * @throws AssertionError - if the actual Feature is not complete.
	 */
	public S isComplete() {
		isNotNull();
		if (!actual.isComplete()) {
			throw failure("%nExpecting%n  <%s>%nto be complete", actual);
		}
		return myself;
	}

	/**
	 * Verifies that the actual Feature is not complete.
	 *
	 * @return this assertion object.
	 * @throws AssertionError - if the actual Feature is complete.
	 */
	public S isNotComplete() {
		isNotNull();
		if (actual.isComplete()) {
			throw failure("%nExpecting%n  <%s>%nnot to be complete", actual);
		}
		return myself;
	}

	/**
	 * Verifies that the actual Feature's description is equal to the given one.
	 *
	 * @param description the given description to compare the actual Feature's
	 *            description to.
	 * @return this assertion object.
	 * @throws AssertionError - if the actual Feature's description is not equal
	 *             to the given one.
	 */
	public S hasDescription(String description) {
		isNotNull();
		String actualValue = actual.getDescription()
			.orElse(null);
		if (!Objects.equals(actualValue, description)) {
			throw failureWithActualExpected(actualValue, description,
				"%nExpecting%n  <%s>%nto have description:%n  <%s>%nbut was:%n  <%s>", actual, description,
				actualValue);
		}
		return myself;
	}

	public S hasDescriptionMatching(String pattern) {
		isNotNull();
		String actualValue = actual.getDescription()
			.orElse(null);
		if (actualValue == null || !actualValue.matches(pattern)) {
			throw failure("%nExpecting%n  <%s>%nto have description matching:%n  <%s>%nbut was:%n  <%s>", actual,
				pattern, actualValue);
		}
		return myself;
	}

	public S isDescriptionEmpty() {
		isNotNull();
		if (actual.getDescription().isPresent()) {
			throw failure("%nExpecting%n  <%s>%nto have empty description%nbut was:%n  <%s>", actual,
				actual.getDescription()
					.get());
		}
		return myself;
	}

	/**
	 * Verifies that the actual Feature's license is equal to the given one.
	 *
	 * @param license the given license to compare the actual Feature's license
	 *            to.
	 * @return this assertion object.
	 * @throws AssertionError - if the actual Feature's license is not equal to
	 *             the given one.
	 */
	public S hasLicense(String license) {
		isNotNull();
		String actualValue = actual.getLicense()
			.orElse(null);
		if (!Objects.equals(actualValue, license)) {
			throw failureWithActualExpected(actualValue, license,
				"%nExpecting%n  <%s>%nto have license:%n  <%s>%nbut was:%n  <%s>", actual, license, actualValue);
		}
		return myself;
	}

	public S hasLicenseMatching(String pattern) {
		isNotNull();
		String actualValue = actual.getLicense()
			.orElse(null);
		if (actualValue == null || !actualValue.matches(pattern)) {
			throw failure("%nExpecting%n  <%s>%nto have license matching:%n  <%s>%nbut was:%n  <%s>", actual, pattern,
				actualValue);
		}
		return myself;
	}

	public S isLicenseEmpty() {
		isNotNull();
		if (actual.getLicense().isPresent()) {
			throw failure("%nExpecting%n  <%s>%nto have empty license%nbut was:%n  <%s>", actual, actual.getLicense()
				.get());
		}
		return myself;
	}

	/**
	 * Verifies that the actual Feature's name is equal to the given one.
	 *
	 * @param name the given name to compare the actual Feature's name to.
	 * @return this assertion object.
	 * @throws AssertionError - if the actual Feature's name is not equal to the
	 *             given one.
	 */
	public S hasName(String name) {
		isNotNull();
		String actualValue = actual.getName()
			.orElse(null);
		if (!Objects.equals(actualValue, name)) {
			throw failureWithActualExpected(actualValue, name,
				"%nExpecting%n  <%s>%nto have name:%n  <%s>%nbut was:%n  <%s>", actual, name, actualValue);
		}
		return myself;
	}

	public S hasNameMatching(String pattern) {
		isNotNull();
		String actualValue = actual.getName()
			.orElse(null);
		if (actualValue == null || !actualValue.matches(pattern)) {
			throw failure("%nExpecting%n  <%s>%nto have name matching:%n  <%s>%nbut was:%n  <%s>", actual, pattern,
				actualValue);
		}
		return myself;
	}

	public S hasNameEmpty() {
		isNotNull();
		if (actual.getName().isPresent()) {
			throw failure("%nExpecting%n  <%s>%nto have empty name%nbut was:%n  <%s>", actual, actual.getName()
				.get());
		}
		return myself;
	}

	/**
	 * Verifies that the actual Feature's vendor is equal to the given one.
	 *
	 * @param vendor the given vendor to compare the actual Feature's vendor to.
	 * @return this assertion object.
	 * @throws AssertionError - if the actual Feature's vendor is not equal to
	 *             the given one.
	 */
	public S hasVendor(String vendor) {
		isNotNull();
		String actualValue = actual.getVendor()
			.orElse(null);
		if (!Objects.equals(actualValue, vendor)) {
			throw failureWithActualExpected(actualValue, vendor,
				"%nExpecting%n  <%s>%nto have vendor:%n  <%s>%nbut was:%n  <%s>", actual, vendor, actualValue);
		}
		return myself;
	}

	public S hasVendorMatching(String pattern) {
		isNotNull();
		String actualValue = actual.getVendor()
			.orElse(null);
		if (actualValue == null || !actualValue.matches(pattern)) {
			throw failure("%nExpecting%n  <%s>%nto have vendor matching:%n  <%s>%nbut was:%n  <%s>", actual, pattern,
				actualValue);
		}
		return myself;
	}

	public S isVendorEmpty() {
		isNotNull();
		if (actual.getVendor().isPresent()) {
			throw failure("%nExpecting%n  <%s>%nto have empty vendor%nbut was:%n  <%s>", actual, actual.getVendor()
				.get());
		}
		return myself;
	}

}
