name: CI Build

on: [push, pull_request]

env:
  LC_ALL: en_US.UTF-8

defaults:
  run:
    shell: bash

jobs:
  JDK_Matrix:
    strategy:
      matrix:
        java: [ 11, 14, 15-ea ]
        os: [ ubuntu-latest ]
        include:
        - os: windows-latest
          java: 8
        - os: ubuntu-latest
          java: 8
          codecov: true
          canonical: ${{ (github.repository == 'osgi/osgi-test') && ((github.ref == 'refs/heads/main') || (github.ref == 'refs/heads/release')) && (github.event_name != 'pull_request') }}
        - os: ubuntu-latest
          java: 8
          experimental: true
          mavenopts: -Pbnd-next
    name: JDK${{ matrix.java }} ${{ matrix.os }} ${{ matrix.mavenopts }}
    runs-on: ${{ matrix.os }}
    steps:
    - name: Git Checkout
      uses: actions/checkout@v2
    - name: Set up Java ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Build
      id: build
      continue-on-error: ${{ matrix.experimental }}
      run: |
        ./.github/scripts/build.sh ${{ matrix.mavenopts }}
    - name: Import GPG key
      id: import_gpg
      if: (matrix.canonical && (steps.build.outcome == 'success'))
      uses: crazy-max/ghaction-import-gpg@v2
      env:
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
    - name: GPG key information
      if: (steps.import_gpg.outcome == 'success')
      run: |
        echo "fingerprint: ${{ steps.import_gpg.outputs.fingerprint }}"
        echo "keyid:       ${{ steps.import_gpg.outputs.keyid }}"
        echo "name:        ${{ steps.import_gpg.outputs.name }}"
        echo "email:       ${{ steps.import_gpg.outputs.email }}"
    - name: Publish
      if: (steps.import_gpg.outcome == 'success')
      run: |
        ./.github/scripts/publish.sh -Possrh
      env:
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
    - name: Upload "assertj.framework" coverage to Codecov
      if: (matrix.codecov)
      uses: codecov/codecov-action@v1.0.12
      with:
        file: ./org.osgi.test.assertj.framework/target/site/jacoco/jacoco.xml
        name: assertj.framework
    - name: Upload "assertj.promise" coverage to Codecov
      if: (matrix.codecov)
      uses: codecov/codecov-action@v1.0.12
      with:
        file: ./org.osgi.test.assertj.promise/target/site/jacoco/jacoco.xml
        name: assertj.promise
    - name: Upload "common" coverage to Codecov
      if: (matrix.codecov)
      uses: codecov/codecov-action@v1.0.12
      with:
        file: ./org.osgi.test.common/target/site/jacoco/jacoco.xml
        name: common
    - name: Upload "junit4" coverage to Codecov
      if: (matrix.codecov)
      uses: codecov/codecov-action@v1.0.12
      with:
        file: ./org.osgi.test.junit4/target/site/jacoco-it/jacoco.xml
        name: junit4
    - name: Upload "junit5" coverage to Codecov
      if: (matrix.codecov)
      uses: codecov/codecov-action@v1.0.12
      with:
        file: ./org.osgi.test.junit5/target/site/jacoco-it/jacoco.xml
        name: junit5
    - name: Upload "junit5.cm" coverage to Codecov
      if: (matrix.codecov)
      uses: codecov/codecov-action@v1.0.12
      with:
        file: ./org.osgi.test.junit5.cm/target/site/jacoco-it/jacoco.xml
        name: junit5.cm
